services:
  postgres:
    image: postgres:17
    container_name: inventory_manager_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory_manager
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: